### ISSUE TITLE
Deploy RIALTO Core + Derivative Datastore to AWS Prod Env

### ISSUE THREAD

**Issue by cmh2166** [sul-dlss/rialto#124] opened 2018-06-25 23:25 UTC
Blocked by #123

**Comment by aaron-collier** [comment] 2018-09-27 23:01
Closing. Dupe.

**Closed by aaron-collier** 2018-09-27 23:01 UTC
Labels: blocked

**Comment by jcoyne** [comment] 2018-10-01 14:56
@aaron-collier what is this a duplicate of?  This ticket was blocking #125, but I don't know how to update that ticket now that this is closed.
